### PR TITLE
Update ne.scheme

### PR DESCRIPTION
**Pull request by khumnath**

### CODE REVIEW

**Comment by khumnath** [comment]
Please review[ this](https://gist.github.com/khumnath/8aef65d79d829f2b75f69c56a2c98186?permalink_comment_id=4795992#gistcomment-4795992) comment for any modifications. Identify what is functioning correctly and what requires improvement.

**Comment by aksharlabs** [comment]
@khumnath can we map full stop for purnavirama?

**Comment by khumnath** [comment]
@aksharlabs Not working that now.  did you tested this scheme file [ne.scheme](https://gist.github.com/khumnath/40ff2899a847d300a6278293a315b762) ? Please test typing and suggest where need improvement.

**Comment by aksharlabs** [comment]
> @aksharlabs Not working that now. did you tested this scheme file [ne.scheme](https://gist.github.com/khumnath/40ff2899a847d300a6278293a315b762) ? Please test typing and suggest where need improvement.

I tested and works fine other than you mentioned above.

**Pull request closed without merging**
